name: example filebeat
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
      - /var/log/**/*.log

output.elasticsearch:
  hosts: ['localhost:9200']

setup.kibana:
  host: 'localhost:5601'
